import type {
  Category,
  Faq,
  Farmer,
  PlatformStat,
  Product,
  Recipe,
  Testimonial,
  TraceStage,
} from "@/types";
export const images = {
  beef: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=1200&q=80",
  goat: "https://images.unsplash.com/photo-1558030134-6afc5d4f5d55?auto=format&fit=crop&w=1200&q=80",
  lamb: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
  poultry:
    "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=1200&q=80",
  farmer1: "https://panagrimedia.com/wp-content/uploads/2022/07/livestock-photo-2-1024x577.jpg",
  farmer2:
    "https://d1jyxxz9imt9yb.cloudfront.net/medialib/5172/image/s1300x1300/LC202403_IllaingarunyoniConservancy_002_581550_reduced.jpg",
  farmer3:
    "https://ilriclippings.wordpress.com/wp-content/uploads/2018/01/17ilri_kapiti_cattleatkapiti04_cropped.jpg",
};
export const categories: Category[] = [
  {
    id: "c1",
    slug: "beef",
    name: "Premium Beef",
    description: "Kenyan quality beef cuts.",
    productCount: 15,
    image: images.beef,
  },
  {
    id: "c2",
    slug: "goat",
    name: "Goat Meat",
    description: "Kenyan quality goat cuts.",
    productCount: 10,
    image: images.goat,
  },
  {
    id: "c3",
    slug: "lamb",
    name: "Highland Lamb",
    description: "Kenyan quality lamb cuts.",
    productCount: 10,
    image: images.lamb,
  },
  {
    id: "c4",
    slug: "poultry",
    name: "Free-range Chicken",
    description: "Kenyan quality poultry cuts.",
    productCount: 15,
    image: images.poultry,
  },
];
export const farmers: Farmer[] = [
  {
    id: "f1",
    slug: "laikipia-highlands",
    name: "Samuel Kiptoo",
    farmName: "Laikipia Highlands Ranch",
    location: "Nanyuki",
    county: "Laikipia",
    verified: true,
    rating: 4.9,
    reviewCount: 864,
    since: 2014,
    story: "Grass-fed cattle ranch.",
    certifications: ["Vet Verified", "Cold Chain Approved"],
    avatar: images.farmer1,
    metrics: { orders: 6200, onTimeRate: 99.1, repeatRate: 74 },
  },
  {
    id: "f2",
    slug: "narok-plains",
    name: "Naserian Ole Saitoti",
    farmName: "Narok Plains Ranch",
    location: "Narok",
    county: "Narok",
    verified: true,
    rating: 4.8,
    reviewCount: 542,
    since: 2016,
    story: "Lamb and goat ranch.",
    certifications: ["Vet Verified"],
    avatar: images.farmer2,
    metrics: { orders: 4100, onTimeRate: 98.5, repeatRate: 69 },
  },
  {
    id: "f3",
    slug: "eldoret-pastures",
    name: "Grace Chebet",
    farmName: "Eldoret Green Pastures",
    location: "Eldoret",
    county: "Uasin Gishu",
    verified: true,
    rating: 4.8,
    reviewCount: 487,
    since: 2018,
    story: "Free-range poultry farmer.",
    certifications: ["Free Range"],
    avatar: images.farmer3,
    metrics: { orders: 3800, onTimeRate: 98.8, repeatRate: 71 },
  },
];
const nutrition = [
  { label: "Protein", value: "26 g" },
  { label: "Fat", value: "12 g" },
  { label: "Calories", value: "212 kcal" },
  { label: "Iron", value: "15%" },
];
export const products: Product[] = [
  {
    id: "p1",
    slug: "nyama-choma-beef",
    name: "Nyama Choma Beef",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 980,
    compareAtPrice: 1078,
    unit: "kg",
    rating: 4.7,
    reviewCount: 95,
    inStock: true,
    stockKg: 21,
    badges: ["Best Seller"],
    origin: "Laikipia",
    image: images.beef,
    description: "Nyama Choma Beef from Laikipia.",
    nutrition,
  },
  {
    id: "p2",
    slug: "beef-fillet",
    name: "Beef Fillet",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1020,
    compareAtPrice: 1122,
    unit: "kg",
    rating: 4.8,
    reviewCount: 100,
    inStock: true,
    stockKg: 22,
    badges: ["Best Seller"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Fillet from Laikipia.",
    nutrition,
  },
  {
    id: "p3",
    slug: "beef-ribeye",
    name: "Beef Ribeye",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1060,
    compareAtPrice: 1166,
    unit: "kg",
    rating: 4.9,
    reviewCount: 105,
    inStock: true,
    stockKg: 23,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Ribeye from Laikipia.",
    nutrition,
  },
  {
    id: "p4",
    slug: "beef-sirloin",
    name: "Beef Sirloin",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1100,
    compareAtPrice: 1210,
    unit: "kg",
    rating: 4.7,
    reviewCount: 110,
    inStock: true,
    stockKg: 24,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Sirloin from Laikipia.",
    nutrition,
  },
  {
    id: "p5",
    slug: "t-bone-steak",
    name: "T-Bone Steak",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1140,
    compareAtPrice: 1254,
    unit: "kg",
    rating: 4.8,
    reviewCount: 115,
    inStock: true,
    stockKg: 25,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "T-Bone Steak from Laikipia.",
    nutrition,
  },
  {
    id: "p6",
    slug: "beef-brisket",
    name: "Beef Brisket",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1180,
    compareAtPrice: 1298,
    unit: "kg",
    rating: 4.9,
    reviewCount: 120,
    inStock: true,
    stockKg: 26,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Brisket from Laikipia.",
    nutrition,
  },
  {
    id: "p7",
    slug: "chuck-roast",
    name: "Chuck Roast",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1220,
    compareAtPrice: 1342,
    unit: "kg",
    rating: 4.7,
    reviewCount: 125,
    inStock: true,
    stockKg: 27,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Chuck Roast from Laikipia.",
    nutrition,
  },
  {
    id: "p8",
    slug: "beef-mince",
    name: "Beef Mince",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1260,
    compareAtPrice: 1386,
    unit: "kg",
    rating: 4.8,
    reviewCount: 130,
    inStock: true,
    stockKg: 28,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Mince from Laikipia.",
    nutrition,
  },
  {
    id: "p9",
    slug: "beef-cubes",
    name: "Beef Cubes",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1300,
    compareAtPrice: 1430,
    unit: "kg",
    rating: 4.9,
    reviewCount: 135,
    inStock: true,
    stockKg: 29,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Cubes from Laikipia.",
    nutrition,
  },
  {
    id: "p10",
    slug: "beef-ribs",
    name: "Beef Ribs",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1340,
    compareAtPrice: 1474,
    unit: "kg",
    rating: 4.7,
    reviewCount: 140,
    inStock: true,
    stockKg: 30,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Ribs from Laikipia.",
    nutrition,
  },
  {
    id: "p11",
    slug: "oxtail",
    name: "Oxtail",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1380,
    compareAtPrice: 1518,
    unit: "kg",
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    stockKg: 31,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Oxtail from Laikipia.",
    nutrition,
  },
  {
    id: "p12",
    slug: "beef-liver",
    name: "Beef Liver",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1420,
    compareAtPrice: 1562,
    unit: "kg",
    rating: 4.9,
    reviewCount: 150,
    inStock: true,
    stockKg: 32,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Liver from Laikipia.",
    nutrition,
  },
  {
    id: "p13",
    slug: "beef-heart",
    name: "Beef Heart",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1460,
    compareAtPrice: 1606,
    unit: "kg",
    rating: 4.7,
    reviewCount: 155,
    inStock: true,
    stockKg: 33,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Heart from Laikipia.",
    nutrition,
  },
  {
    id: "p14",
    slug: "beef-sausages",
    name: "Beef Sausages",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1500,
    compareAtPrice: 1650,
    unit: "kg",
    rating: 4.8,
    reviewCount: 160,
    inStock: true,
    stockKg: 34,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Sausages from Laikipia.",
    nutrition,
  },
  {
    id: "p15",
    slug: "beef-shank",
    name: "Beef Shank",
    categorySlug: "beef",
    categoryName: "Premium Beef",
    farmerId: "f1",
    price: 1540,
    compareAtPrice: 1694,
    unit: "kg",
    rating: 4.9,
    reviewCount: 165,
    inStock: true,
    stockKg: 35,
    badges: ["Fresh"],
    origin: "Laikipia",
    image: images.beef,
    description: "Beef Shank from Laikipia.",
    nutrition,
  },
  {
    id: "p16",
    slug: "goat-ribs",
    name: "Goat Ribs",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 850,
    compareAtPrice: 935,
    unit: "kg",
    rating: 4.7,
    reviewCount: 170,
    inStock: true,
    stockKg: 36,
    badges: ["Best Seller"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Ribs from Narok.",
    nutrition,
  },
  {
    id: "p17",
    slug: "goat-leg",
    name: "Goat Leg",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 890,
    compareAtPrice: 979,
    unit: "kg",
    rating: 4.8,
    reviewCount: 175,
    inStock: true,
    stockKg: 37,
    badges: ["Best Seller"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Leg from Narok.",
    nutrition,
  },
  {
    id: "p18",
    slug: "goat-shoulder",
    name: "Goat Shoulder",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 930,
    compareAtPrice: 1023,
    unit: "kg",
    rating: 4.9,
    reviewCount: 180,
    inStock: true,
    stockKg: 38,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Shoulder from Narok.",
    nutrition,
  },
  {
    id: "p19",
    slug: "goat-chops",
    name: "Goat Chops",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 970,
    compareAtPrice: 1067,
    unit: "kg",
    rating: 4.7,
    reviewCount: 185,
    inStock: true,
    stockKg: 39,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Chops from Narok.",
    nutrition,
  },
  {
    id: "p20",
    slug: "goat-cubes",
    name: "Goat Cubes",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 1010,
    compareAtPrice: 1111,
    unit: "kg",
    rating: 4.8,
    reviewCount: 190,
    inStock: true,
    stockKg: 40,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Cubes from Narok.",
    nutrition,
  },
  {
    id: "p21",
    slug: "goat-liver",
    name: "Goat Liver",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 1050,
    compareAtPrice: 1155,
    unit: "kg",
    rating: 4.9,
    reviewCount: 195,
    inStock: true,
    stockKg: 41,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Liver from Narok.",
    nutrition,
  },
  {
    id: "p22",
    slug: "goat-neck",
    name: "Goat Neck",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 1090,
    compareAtPrice: 1199,
    unit: "kg",
    rating: 4.7,
    reviewCount: 200,
    inStock: true,
    stockKg: 42,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Neck from Narok.",
    nutrition,
  },
  {
    id: "p23",
    slug: "whole-goat",
    name: "Whole Goat",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 1130,
    compareAtPrice: 1243,
    unit: "kg",
    rating: 4.8,
    reviewCount: 205,
    inStock: true,
    stockKg: 43,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Whole Goat from Narok.",
    nutrition,
  },
  {
    id: "p24",
    slug: "goat-mince",
    name: "Goat Mince",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 1170,
    compareAtPrice: 1287,
    unit: "kg",
    rating: 4.9,
    reviewCount: 210,
    inStock: true,
    stockKg: 44,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Mince from Narok.",
    nutrition,
  },
  {
    id: "p25",
    slug: "goat-sausage",
    name: "Goat Sausage",
    categorySlug: "goat",
    categoryName: "Goat Meat",
    farmerId: "f2",
    price: 1210,
    compareAtPrice: 1331,
    unit: "kg",
    rating: 4.7,
    reviewCount: 215,
    inStock: true,
    stockKg: 45,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.goat,
    description: "Goat Sausage from Narok.",
    nutrition,
  },
  {
    id: "p26",
    slug: "lamb-chops",
    name: "Lamb Chops",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1350,
    compareAtPrice: 1485,
    unit: "kg",
    rating: 4.7,
    reviewCount: 220,
    inStock: true,
    stockKg: 46,
    badges: ["Best Seller"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Chops from Narok.",
    nutrition,
  },
  {
    id: "p27",
    slug: "lamb-rack",
    name: "Lamb Rack",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1390,
    compareAtPrice: 1529,
    unit: "kg",
    rating: 4.8,
    reviewCount: 225,
    inStock: true,
    stockKg: 47,
    badges: ["Best Seller"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Rack from Narok.",
    nutrition,
  },
  {
    id: "p28",
    slug: "lamb-leg",
    name: "Lamb Leg",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1430,
    compareAtPrice: 1573,
    unit: "kg",
    rating: 4.9,
    reviewCount: 230,
    inStock: true,
    stockKg: 48,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Leg from Narok.",
    nutrition,
  },
  {
    id: "p29",
    slug: "lamb-shoulder",
    name: "Lamb Shoulder",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1470,
    compareAtPrice: 1617,
    unit: "kg",
    rating: 4.7,
    reviewCount: 235,
    inStock: true,
    stockKg: 49,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Shoulder from Narok.",
    nutrition,
  },
  {
    id: "p30",
    slug: "lamb-shank",
    name: "Lamb Shank",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1510,
    compareAtPrice: 1661,
    unit: "kg",
    rating: 4.8,
    reviewCount: 240,
    inStock: true,
    stockKg: 50,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Shank from Narok.",
    nutrition,
  },
  {
    id: "p31",
    slug: "lamb-ribs",
    name: "Lamb Ribs",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1550,
    compareAtPrice: 1705,
    unit: "kg",
    rating: 4.9,
    reviewCount: 245,
    inStock: true,
    stockKg: 51,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Ribs from Narok.",
    nutrition,
  },
  {
    id: "p32",
    slug: "lamb-mince",
    name: "Lamb Mince",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1590,
    compareAtPrice: 1749,
    unit: "kg",
    rating: 4.7,
    reviewCount: 250,
    inStock: true,
    stockKg: 52,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Mince from Narok.",
    nutrition,
  },
  {
    id: "p33",
    slug: "lamb-cubes",
    name: "Lamb Cubes",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1630,
    compareAtPrice: 1793,
    unit: "kg",
    rating: 4.8,
    reviewCount: 255,
    inStock: true,
    stockKg: 53,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Cubes from Narok.",
    nutrition,
  },
  {
    id: "p34",
    slug: "lamb-liver",
    name: "Lamb Liver",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1670,
    compareAtPrice: 1837,
    unit: "kg",
    rating: 4.9,
    reviewCount: 260,
    inStock: true,
    stockKg: 54,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Lamb Liver from Narok.",
    nutrition,
  },
  {
    id: "p35",
    slug: "whole-lamb",
    name: "Whole Lamb",
    categorySlug: "lamb",
    categoryName: "Highland Lamb",
    farmerId: "f2",
    price: 1710,
    compareAtPrice: 1881,
    unit: "kg",
    rating: 4.7,
    reviewCount: 265,
    inStock: true,
    stockKg: 55,
    badges: ["Fresh"],
    origin: "Narok",
    image: images.lamb,
    description: "Whole Lamb from Narok.",
    nutrition,
  },
  {
    id: "p36",
    slug: "whole-free-range-chicken",
    name: "Whole Free-range Chicken",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 520,
    compareAtPrice: 572,
    unit: "bird",
    rating: 4.7,
    reviewCount: 270,
    inStock: true,
    stockKg: 56,
    badges: ["Best Seller"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Whole Free-range Chicken from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p37",
    slug: "chicken-drumsticks",
    name: "Chicken Drumsticks",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 560,
    compareAtPrice: 616,
    unit: "kg",
    rating: 4.8,
    reviewCount: 275,
    inStock: true,
    stockKg: 57,
    badges: ["Best Seller"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Drumsticks from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p38",
    slug: "chicken-thighs",
    name: "Chicken Thighs",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 600,
    compareAtPrice: 660,
    unit: "kg",
    rating: 4.9,
    reviewCount: 280,
    inStock: true,
    stockKg: 58,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Thighs from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p39",
    slug: "chicken-wings",
    name: "Chicken Wings",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 640,
    compareAtPrice: 704,
    unit: "kg",
    rating: 4.7,
    reviewCount: 285,
    inStock: true,
    stockKg: 59,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Wings from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p40",
    slug: "chicken-breast",
    name: "Chicken Breast",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 680,
    compareAtPrice: 748,
    unit: "kg",
    rating: 4.8,
    reviewCount: 290,
    inStock: true,
    stockKg: 60,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Breast from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p41",
    slug: "boneless-chicken-thigh",
    name: "Boneless Chicken Thigh",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 720,
    compareAtPrice: 792,
    unit: "kg",
    rating: 4.9,
    reviewCount: 295,
    inStock: true,
    stockKg: 61,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Boneless Chicken Thigh from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p42",
    slug: "chicken-cubes",
    name: "Chicken Cubes",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 760,
    compareAtPrice: 836,
    unit: "kg",
    rating: 4.7,
    reviewCount: 300,
    inStock: true,
    stockKg: 62,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Cubes from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p43",
    slug: "chicken-mince",
    name: "Chicken Mince",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 800,
    compareAtPrice: 880,
    unit: "kg",
    rating: 4.8,
    reviewCount: 305,
    inStock: true,
    stockKg: 63,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Mince from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p44",
    slug: "chicken-liver",
    name: "Chicken Liver",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 840,
    compareAtPrice: 924,
    unit: "kg",
    rating: 4.9,
    reviewCount: 310,
    inStock: true,
    stockKg: 64,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Liver from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p45",
    slug: "chicken-gizzards",
    name: "Chicken Gizzards",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 880,
    compareAtPrice: 968,
    unit: "kg",
    rating: 4.7,
    reviewCount: 315,
    inStock: true,
    stockKg: 65,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Gizzards from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p46",
    slug: "chicken-neck",
    name: "Chicken Neck",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 920,
    compareAtPrice: 1012,
    unit: "kg",
    rating: 4.8,
    reviewCount: 320,
    inStock: true,
    stockKg: 66,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Neck from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p47",
    slug: "kienyeji-chicken",
    name: "Kienyeji Chicken",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 960,
    compareAtPrice: 1056,
    unit: "bird",
    rating: 4.9,
    reviewCount: 325,
    inStock: true,
    stockKg: 67,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Kienyeji Chicken from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p48",
    slug: "smoked-chicken",
    name: "Smoked Chicken",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 1000,
    compareAtPrice: 1100,
    unit: "kg",
    rating: 4.7,
    reviewCount: 330,
    inStock: true,
    stockKg: 68,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Smoked Chicken from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p49",
    slug: "family-chicken-pack",
    name: "Family Chicken Pack",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 1040,
    compareAtPrice: 1144,
    unit: "kg",
    rating: 4.8,
    reviewCount: 335,
    inStock: true,
    stockKg: 69,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Family Chicken Pack from Uasin Gishu.",
    nutrition,
  },
  {
    id: "p50",
    slug: "chicken-sausages",
    name: "Chicken Sausages",
    categorySlug: "poultry",
    categoryName: "Free-range Chicken",
    farmerId: "f3",
    price: 1080,
    compareAtPrice: 1188,
    unit: "kg",
    rating: 4.9,
    reviewCount: 340,
    inStock: true,
    stockKg: 70,
    badges: ["Fresh"],
    origin: "Uasin Gishu",
    image: images.poultry,
    description: "Chicken Sausages from Uasin Gishu.",
    nutrition,
  },
];
export const traceStages: TraceStage[] = [
  {
    id: "t1",
    title: "Ranch",
    description: "Livestock registered.",
    duration: "6–24 months",
    metric: "Animal ID",
  },
  {
    id: "t2",
    title: "Veterinary Check",
    description: "Inspection.",
    duration: "Pre-dispatch",
    metric: "Certificate",
  },
  {
    id: "t3",
    title: "Transport",
    description: "Temperature-controlled.",
    duration: "<3 hrs",
    metric: "2–4°C",
  },
  {
    id: "t4",
    title: "Processing",
    description: "Licensed facility.",
    duration: "Same day",
    metric: "Batch ID",
  },
  {
    id: "t5",
    title: "Packaging",
    description: "Vacuum-sealed.",
    duration: "1 hr",
    metric: "QR Code",
  },
  {
    id: "t6",
    title: "Cold Storage",
    description: "Monitored.",
    duration: "0–24 hrs",
    metric: "0–2°C",
  },
  {
    id: "t7",
    title: "Delivery",
    description: "Chilled delivery.",
    duration: "Next day",
    metric: "Live ETA",
  },
];
export const testimonials: Testimonial[] = [
  {
    id: "r1",
    name: "Faith Wanjiku",
    role: "Restaurant Owner • Nairobi",
    quote: "Consistent quality every week.",
    rating: 5,
  },
  {
    id: "r2",
    name: "Brian Mwangi",
    role: "Home Customer • Kiambu",
    quote: "I know where my meat comes from.",
    rating: 5,
  },
  {
    id: "r3",
    name: "Chef Kevin Otieno",
    role: "Executive Chef • Westlands",
    quote: "Traceability builds confidence.",
    rating: 5,
  },
];
export const platformStats: PlatformStat[] = [
  { id: "s1", label: "Verified Ranches", value: 126, suffix: "+" },
  { id: "s2", label: "Orders Delivered", value: 18500, suffix: "+" },
  { id: "s3", label: "On-Time Delivery", value: 98.7, suffix: "%" },
  { id: "s4", label: "Average Rating", value: 4.8 },
];
export const recipes: Recipe[] = [
  {
    id: "rc1",
    title: "Nyama Choma Beef",
    minutes: 45,
    difficulty: "Medium",
    cut: "Beef",
    image: images.beef,
  },
  {
    id: "rc2",
    title: "Goat Fry",
    minutes: 55,
    difficulty: "Medium",
    cut: "Goat",
    image: images.goat,
  },
  {
    id: "rc3",
    title: "Chicken Pilau",
    minutes: 40,
    difficulty: "Easy",
    cut: "Chicken",
    image: images.poultry,
  },
];
export const faqs: Faq[] = [
  { id: "q1", question: "How is freshness guaranteed?", answer: "Cold-chain monitored." },
  { id: "q2", question: "Can businesses order in bulk?", answer: "Yes." },
  { id: "q3", question: "How are farmers verified?", answer: "Vet inspections." },
  {
    id: "q4",
    question: "Where do you deliver?",
    answer: "Nairobi, Kiambu and expanding counties.",
  },
];
export const partners = [
  "Carnivore",
  "Java House",
  "Sarova Hotels",
  "Talisman",
  "Artcaffe",
  "Nyama Mama",
];
